---
name: pumrporder:IDTAG
clusters:
  pumrporderIDTAG:
    services:
      breed:
        name: pumrporder:IDTAG
        deployable: partsunlimitedmrp/orderapi:IDTAG
        ports:
          webport: 8080/http
      scale:
        cpu: 1      
        memory: 1024MB
        instances: 1